name: snowflake-devops-demo3

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Determine environment based on branch
      - name: Determine environment
        run: |
          echo "Branch: $GITHUB_REF_NAME"
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            echo "ENV=PRD" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF_NAME" == "develop" ]]; then
            echo "ENV=DEV" >> $GITHUB_ENV
          else
            echo "ENV=DEV" >> $GITHUB_ENV
          fi
          echo "Environment set to: $ENV"

      # Install schemachange and Jinja2
      - name: Install schemachange
        run: |
          pip install --upgrade pip
          pip install schemachange==3.7.0 jinja2

      # Run schemachange with branch-based ENV
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          CHANGE_HISTORY_TABLE="${SF_DATABASE}.${SF_SCHEMA}.CHANGE_HISTORY_${ENV}"
          echo "Using change history table: $CHANGE_HISTORY_TABLE"
          
          echo "Running schemachange for environment: $ENV"
          schemachange -f $GITHUB_WORKSPACE/migrations \
                       -a $SF_ACCOUNT \
                       -u $SF_USERNAME \
                       -r $SF_ROLE \
                       -w $SF_WAREHOUSE \
                       -d $SF_DATABASE \
                       -c $CHANGE_HISTORY_TABLE \
                       --create-change-history-table \
                       --vars '{"ENV": "'"$ENV"'"}'
